# Generated by Django 5.0.6 on 2024-06-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_job_remove_photo_vehicle_alter_inspection_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
