# Generated by Django 5.0.6 on 2024-06-12 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_remove_vehicle_job_delete_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='session',
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PhotoSession',
        ),
    ]
