# Generated by Django 5.0.6 on 2024-06-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_remove_photo_session_inspection_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection'),
        ),
    ]
